### ISSUE TITLE
DistributionNotFound: pip==6.1.1

### ISSUE THREAD

**Issue by aidylewis** [satori-com/mzbench#123]
Hi, 

I am trying to install from source, but when I attempt to install the Python requirements, I receive a distribution not found error. 

```
python --version
Python 2.7.12
```

Thanks 

```
sudo pip install -r mzbench/requirements.txt
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==6.1.1
```

**Comment by timofey-barmin** [comment]
Hi,
https://stackoverflow.com/questions/6200056/pip-broke-how-to-fix-distributionnotfound-error
